### ISSUE TITLE
PM3D-Calibration missing data NC01

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/On-farm-Protocols#480]
## Description ##

- [ ] No azure data for CC 2024 TM1, transects 1, 2 and 3 - Biomass is present
- [ ] No azure data for CC 2024 TM3, transects 1, 3, 4 and 5
- [ ] No biomass data for CC 2024 TM1, Mix4, quadrat 1

## Task Category
- Data Shepherding

## Type of User ##
- Calibrator

## User Code ##
- NC-Reberg-Horton

## Point of Contact ##
- @marialauracangiano
